version: "3"

services:
  app:
    build:
      context: flask
    ports:
      - "5000:5000"

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
