"""Added add_date column to history table

Revision ID: 6e30a329b9ab
Revises: 5ed40a5b157a
Create Date: 2021-09-08 11:26:46.818672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e30a329b9ab'
down_revision = '5ed40a5b157a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('add_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'add_date')
    # ### end Alembic commands ###
